dubbo:
  application:
    name: product-service
  protocol:
    name: dubbo
    port: 27072
  registry:
    address: zookeeper://127.0.0.1:2181


server:
  port: 7072
spring:
  application:
    name: product-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/product?serverTimezone=Asia/Shanghai&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: Admin123#
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 28740000
      maximum-pool-size: 5
      minimum-idle: 3
      pool-name: DatebookHikariCP

mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    xyz.mqiy.demo.dao : debug