dubbo:
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: xyz.mqiy.demo.service
spring:
  application:
    name: spring-boot-dubbo-demo
server:
  port: 7071