server:
  port: 7071

dubbo:
  protocol:
    name: dubbo
    port: 27071
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: xyz.mqiy.demo.service
spring:
  application:
    name: mqiy-product
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/product?serverTimezone=Asia/Shanghai&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: Admin123#
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 28740000
      maximum-pool-size: 5
      minimum-idle: 3
      pool-name: DatebookHikariCP

mybatis:
  configuration:
    map-underscore-to-camel-case: true
