dubbo:
  application:
    name: member-service
  protocol:
    name: dubbo
    port: 27070
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: xyz.mqiy.demo.service
spring:
  application:
    name: member-service
server:
  port: 7070